name: Build and Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Check if Gemfile exists
        id: check-gemfile
        run: |
          if [ -f Gemfile ]; then
            echo "Gemfile exists"
            echo "gemfile_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Gemfile does not exist"
            echo "gemfile_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Install Dependencies
        if: steps.check-gemfile.outputs.gemfile_exists == 'true'
        run: bundle install
        working-directory: ${{ github.workspace }}

      - name: Build Jekyll Site
        run: bundle exec jekyll build
        working-directory: ${{ github.workspace }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: main
          force_orphan: true